test = {   'name': 'q1_4',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> assert type(review_columns) != type(...)\n', 'hidden': False, 'locked': False},
                                   {   'code': ">>> assert set(review_columns) == set(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',\n...        'Sentiment_Subjectivity'])\n",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
