test = {   'name': 'q3.2.4',
    'points': [0.25, 0.25],
    'suites': [   {   'cases': [   {'code': ">>> assert 'FK_Grade_Score' in speeches_df.keys()\n", 'hidden': False, 'locked': False},
                                   {   'code': ">>> from pandas.api.types import is_numeric_dtype;\n>>> assert is_numeric_dtype(speeches_df['FK_Grade_Score'].dtype)\n",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
