test = {   'name': 'q2_4',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> assert cleaned_repub_5_line != ...\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # It looks like the variable still ends with a new line character;\n>>> assert not cleaned_repub_5_line.endswith("\\n")\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> # It looks like you might have accessed the 6th line. Remember about 0-indexing in python.;\n>>> assert cleaned_repub_5_line != ''\n",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert cleaned_repub_5_line.startswith("Florida and Ohio each have a large number")\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
